step-runner-config:
    global-defaults:
        container-registries:
            registry.redhat.io:
                password: ENC[AES256_GCM,data:elsnUp0PVdyRctGOeuKm+Z5mjx4vr7oSm12qPZjHiGUh9T/MYHG1yu1EBpqtjtUd4Ht78ZRO9NTH7JgnMdI8P8c3TiF0+CY5VEaXHNCxihThlwtZ7iT6e+uBH/NbHfBOMk/Yj9MS54k0xz8c+weTvP/8TPjTDszt7vIGnhaRl3No3wdnb61FEw6pV1XP2sqhnxmQG6Nrm/TW9AHInpZVAve4SXpYYQ1FgUlnryjlFLcOMRc/s+/aNn+RYn+kUEdEl2QevtTHD5kCBdwoYkCTZGwHdALDKaSnzySoQKtj/sDTQtXGEgptgEc/KmsmLQDjSsUBANCqgER9mIx5WqcZqP7FbCuwqJtkrKaxPajBkPQXLpZIbgKlpGB/P8VYJ2LLdnzvdme3NbMinRo16X2OmntFgbv+v6b34gE7Q2PqO8lpjycmnNo87zm43MLgTzH6HdRne9t2+q0Xg6kJxmTd/b3mhxyFWCUFKH8LnqBe4yqAEhX8wRJAaAFc6hQA5d9NZD56CG5lXoEN/zvEj06ToudwwVi7hUKe+2xu5Eews4E9E9xM5fipC2GULSfgxlZ+fIbbH5Yr7cv3WHE8KdN/xywZxvGXG+JceYA7lCBsJFLswjhK1CBObyCFKu+ynQwV806fjm8OUmg8rBM5jAsJF4Xp3ExSGPIEZ6xcKUBhSzB4Lv/ykLDV9NQuPC40bqC3q7K6u0F2hu90R33X1EBnv1PWzXQ0qf4PEsAn7RLBzm58dlwolUpNH8ixa3ePPrP9rinITVkehV0DAHINPhfEOo6mSVnBg3vXovLmd+3H6jq8GSTzcpzN/x3H4By2D2/caEWDEkM92PC1ycpAYt3Wbc65bd5dY+B+JuZLqvf6s4hAQR6wKVEI1gUjPhs9lsTBJNTBU6jarSxBj9nNiZNyrfi9q1mEiUipUi2g/6pVz6eEXjAld8A7pp9le2X2XUG1cuqXlP/hMWaFw3l/qtI34Azyssa3Ho6X4+HPlhJretETV1wwzCCZwkQ=,iv:cwfeEodcW7pUc07r2tU7g5wFz1YzoBnCuFlYAaovKfQ=,tag:96x/L+Uqf90gBKMocNSbjQ==,type:str]
            quay-quay-enterprise.apps.tssc.rht-set.com:
                password: ENC[AES256_GCM,data:xxgB8W/kV9ifguZryuuyycZm+8uUDXmCvUeajBhLxOQ+bStbZZgSb33suWBgMApV/WWnJjrPZRvHhMqq6FTUrA==,iv:fNpTzA6xhtWYr0QOmQZNnvViRTcEnrz5WlHEi9ET5oc=,tag:EcOZBWWPrlD0B6knIDsRtg==,type:str]
        maven-servers:
            internal-mirror:
                password: ENC[AES256_GCM,data:NI4bE+WRybjk7+2nge6tYGKm,iv:PnB0m1qi7b6SbgAHFNoEjd6I/8wChmwpBYyJKtY5QAs=,tag:7iNUiCofkefUXpekdk8wng==,type:str]
    deploy:
    -   implementer: ArgoCD
        config:
            argocd-password: ENC[AES256_GCM,data:2oMJ4c1E,iv:j93Gt3IDdjEcUWT5J0EhWjqttVUipF2RumS4PmUaMf0=,tag:IjjuH2005j5Oc97zd9g7lg==,type:str]
            git-password: ENC[AES256_GCM,data:czb7foFRQOWH/XNS,iv:hVzfQZ9c3DQLN9o2wuE3DAtLQ+z62ty2QVq6v1FQLq4=,tag:ML2bTk8753WMIjl9KMV7bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-18T21:56:19Z'
    mac: ENC[AES256_GCM,data:vc3f1KLnKDS0Ts2C5RQlNmIDBI+mt+jqRi56VpUvhgxwWp4gyGEkqi5t+slUwjwktwJ5wBTVmYbshzrF/XjbwgBifCnmfEXmtJoExzRYcpx05nWpWHpBn1bfydRZVozdxpF5vXgjlawLsQwZZMUE6jRas5pnZGuAxbycfJSN9lc=,iv:9JBfTzDSAitslVo/JEgT9G9I6o4gJOLRUrOWuAatt48=,tag:Igzsmohk0tb2Grer28xV8g==,type:str]
    pgp:
    -   created_at: '2020-09-28T12:23:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQgAtBGcv6b0l4J9ws9KzO65M7zWL4oh1F39HDqIGd9kRb3F
            0UApgclYBHokls9L/88H42x9RW8QoCMt3qkd97MtjDx+L06aglLUomO8kszBXbYe
            2SC5G6+7vuZW4k26kbkUJmoTvqi2MRhKvF8gzHlf06HthO9tS2Hx5p7AbKhMBl3b
            bmOBkyMLdsqI+zNaHhvvxCSW0jAjXXQZTyaDkGBPNMi85dcsH2MEmUwgypedM1O6
            nI3Ulx4C5+tm4LACFMBNKXLWQ+FMIbuyXkNJNj4UbgoOE2IxPFyg0N2jV4ybHxW7
            epk06Z0noiIIZLhuHAQEtoa+UN3tRD7Z8dqBiQ/IRtJeASHFjXGivUy7/oy7S9ZW
            kWaMVBTjt35gyGq50/3ng85lyd7RwzkohnncTLoAe9k4UpDLz4YHKN3vSgIW2Ife
            eAGaDZRjd+Lfbn/4qmkHbgWnhVqyC9yrl/a0wZhZwg==
            =WkKu
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T12:28:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/pHJVB+8SuwARAApw1pSjqvOmwVs7PNTgMsFCM4evjE8vdBnL5k35yNOp2B
            C2A2ZRhZbE9nESoc8Jle8l2h0yasNcH2cvIo5KkdyGJTC9fhzZRY4NbiAqU6TW9Q
            j+mpi3qhzzGn+v6C4waqqzuuxKyCbEc2eYZB9xF/fZNZas4HJSHUSk/t+N/XUbAM
            ANJE77Sok1EBVGyZ9z2ketxMs4XgxWNUkzpkulAO7X8hOuvS9uDsh3+LrGrKG/58
            TjlvjWok6dZKW383EyBFgEIjlhpYIc4H3qrWSHq8pLPA1cDLMJTF2erhctNUKtAb
            4wYJbBvRsYqBeCeMRoAVIi97BdLXDR2MKOpAryL2aLrWBRKo7fEIYD+icbcOHxny
            TcJhTvATeMubeP0Z6KsjPNoc+OviPl+L7Io9/bBTAzru+KRXdHvgmNeIda1EBtgX
            IxG43iYiWP5H14MD2Hr68mK30JGLN/xCl13LmF7NzGIfSMVpgo6cff/nwDpt0BpI
            8zZjHDyJ6txZU838+5lR+poxgPcLTydYMwhFH2P4WbkOw2lg3YiswKQqR2bDTR14
            c6CM8Aoid3rX5Vjjupd6dkJ7Va4v7RcYOrPh3hsyCXbCf0l8l2QMB6Blrumysqng
            D4uIUwnlhk+0uh1YyR/daEtnzQATt55meBZgTHQw6CL6dimjcV+qjCmWEdRyOkXS
            XgHz2snMiwuJJa60Ii7uDP2MOauCetubwW4UjbEkDgcVCFkQ+G2FG9vL+5clp9Py
            xqi7GRyrq+MErEKCSbUJIIxw+mtvo0Ynme0nuZujtdfheX6ZLs8lFPQWzGgRi5E=
            =YFT3
            -----END PGP MESSAGE-----
        fp: 355C11B55E83B15E5CF6366283637FAF9D7905E1
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/JEnAHZDjB7AQf8DWskEvdM99XVaLaCCNawymz2Au7MQiPg0QKC3BWF2Qqq
            lY2SRvCqAFt8z7RoNWkYWiBZG2ZrmhtWPbeIY553+dwm19fp3B6wbjOSDBPDeGmd
            xcVA5N28ugzrE3vI0YxZseorcIKMRl+o4lJsJol2FL5D5obEnmMV1tF88DHTkfrn
            oa5EchJz+/BaR5uFTenutpaJ5RysHWRlVKZoVQV2O85xbZaOPN5QsVC6iLa9K0Cu
            vGjqNuQ7FeuWaeU7U7VZbXIw1ZMSVScNcyGQqwOW2rrjtyvIg9uhO7+dgNcjmWF/
            +M5cZygLmvTI0lwgzimISmWvzFRFa2yfxifI21Yaj9JeAQnuzN5Z85YaB6uZjW2r
            XGNdVXVBBsSRnKsK9jLnEFriS3DMbwjdlyFPYmuPYuGwUMY7VYOM0eaweRInir2X
            i8uwt8yKF+sy5Tywwro9gAKDIGYAVLLO1BJyyUVmgw==
            =hEH6
            -----END PGP MESSAGE-----
        fp: 2A25DA15018235A6206921952730D7A70EC35190
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6220UozeaaQAQ//etIica82tTTYZknkn5vvVnFTsFWlYuom15ofv5EUJh1F
            v/1uhvRsDMmyV1vF5JKE/y4a+51SpV/xEqBHTkUD7ffzCFC9IrWpCqGniXO/YY65
            2JPoPEIzHTv1YrWzLq+xqioGIWIBupxULST6AtUjUjMUEPgA6//ANFkr7G1OXA3k
            d4LY2t51uO0pv8REq+cQ+682hOHO3PuNvMSR9KV03lIK5oFzibvEhwXrhVXN5X+b
            81q0zOny/gXLSa+VGP1PpAlzkOi4GOaxintsN7RsjAJjpISTYBmL9BGHFKDm3v0X
            MGcQE03+ocfDgrilNo5CfZutoWWUkKprbeK0kqBXxsy7OWzulYNT+/SgFuO26YsR
            DZcVxuRfaVFgxwjtq78RCuPufjO1/B4L0W4p0vxJjh1NJGMTMxKkr9vXvyMT4rOn
            e8uI56RNDDtogd00dZ9i/CNSxMM6szFl4lZr+ipuIK7fqc2j6nDmFGBRi0KBYVcd
            EXjFLfLHK3QIN/pphdW433hPOn6EP23L1VB6r6CxNRyG5NDlxqCsCJh4Ya2G9kW6
            cUvDriRPjhm24E7VpNBqOB4rFgAEHnzYZ+aDWKP0FWLfP3bupBUFC4rMhYkKtzxc
            AxpVrDDhkpNbE82NWHU/vZYV/s/ZuOa1UBK2l5DkL333BqTy/AhoRdHwY7FK5XzS
            XgELFfS+7xjQliIewSFrmOrEGcXItBpfl7uF1sKzNSS6qUowC5QB6Pdx3u3/VMmL
            utBjcyxDXjaVrId/9OcFmTjB4EYd2R+zpnwDDfajVtqHVY3gx4MB5jE/JXyUWPw=
            =toy5
            -----END PGP MESSAGE-----
        fp: DA7B00C8ACAFED2DA7E33D1ADFA8C968E1F69B13
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx6ne7Mq17RmAQ/+NB8b060MHTdiKLXQw4/YdcURKXPTP5DFLCdu/x8Vav+3
            x50jnVI8r3y8P1Cm9TUtnBOXEJ52FQMi1YP3B/5J3Z+b0rtB94x6Ooq2k2X+N8h/
            kqcMXZfxH4dyosRZV6/Ey4+JQTxpWUTz/S2sUYojFDnD0//2rSpB/3mBblzWI3SK
            6VeyP1BqUqYpSHToU//BY3dIJ7nC+Mc5bn24kPQ9PDjgPsYaXDUcY068KsQpLkAf
            ZuxNqtkWYxYZdKM+BkXDmYYTAMXwDJ0oBXoB1D9FXH0TjVn6CSIBrBJNZfw6G5eP
            hFC7xIkWUnmh/yGOgsBg4xUB4mxELglr5E5eB3W3Az+OLlLrrHpkuLTfnoen7O4t
            1NmGA6P65vxtZW5Q5ryIdpQNfCnfIzmP2GK4gO3fa8s7vT3nWvpxgwwdqfn1qHaw
            THHMlkCZMG9YU8M8vwM+HDxTR8JL7FxwHS6e8Yo3cm21z0fxAuGuGy5gpi6eWZS8
            0OitAgxE49PBxcZcq22ZO6an11QosRAeZ0ByEnT0JH8aF33Nree9yU2TEUNswmti
            DNMtv14CYmuM1vTZ38lzwTcWfomCqjKEKLbK/rFGALZkMrcF4AxPwaoK+qr4MX7R
            VFWRmnOT0A35wtPA3YeZuXNLY9zHv88L5BfNNaGvnsPIUF+qPyfhEd1/pzWiBo7S
            XgFyo3lu8Cg9edpEPvBBIwwsa6A7ZpRpPTd3lkRvKUMZQQVuCniQ4peYAQ0Vwc9p
            z6CKz8bn5mreCHSg5R31umMLdUjWXr4AYKS7w9aZ+btPQMqde6ZyEP0wlawR1wQ=
            =sezO
            -----END PGP MESSAGE-----
        fp: 911B366FD384B2CF3BCAE8EE01F9B7BD00DCD57B
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75NWiDtWcDHAQ/8DRElLp7fraxj+eqPr2NplJVyYPsePCPaQs/PrnmzK1dv
            NrAaK+fVNZPn9RO/Uk7+SI3Kyr3jE2iokPrwsIuVPdwMPip0wzHTvnuNYCLvrNzk
            zx0CDVuB3U3cWDX4YIfhZUEHtoj2vFavEJ0ihpVev1wtPS8eZQ+6PkI0FSlqtvV4
            jczckz/rvF3pquGfDyQH2GpHKr8y758DtRs5DhWPNl8LkrNbFSzw10x0ZICU5Vud
            BpvcnDaBRomPNdYX6lju0taAzw/UvR9VLcl7JQZnps80SqysU+ogjX+nBex6n6it
            B2sGjwvtHDCOYx0cECMCNx4LR1kZ7AIX32yb+/w+xTfttVtvLaLqUIHYZYeM6WdR
            ySaElrx6vjmU/w96SVnuFIvVQ2Ub4u987G6H9FiOz6NOkkIL+TLZCgovJycRqOCn
            yJ+/FQOHyv50AYVyaguMXz84O3+8AfouSgnBs/32S3uBO7VlTOMICTT4LLg+MY5U
            ijY7fkAt43gw8dh5ItAT/l23qVOy4aJN6vJImNEgGiXYS57f9CVLQG+SwY3UK8tg
            gFwzFsD3OBoucR4yxR9CvOkHqQrGjO1GpjX5TjOvEQq01wpsvhkX7i7g+C9RARs+
            /2dca5bUXwcuiyKjCYRqrF2qajXCBoj61A9OKilywsGZsDjhcMKj9y/ScbbhVpvS
            XgEgLgV+ElcaszMciis8FhdzT6fOCyfaIs2ivZsxZYKB+syqbAv5zZ8DsQYqkjAo
            zEAHxfZ0JS3gG5PWKYiMkTHS4v1FWW1+0Swe8DRs2BK5stfMiL4nutQFR2a2MA4=
            =Yere
            -----END PGP MESSAGE-----
        fp: 4A4B9A8F518CD36766AF86DE065BDAD92D70F679
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/haI43zIlNcAQv/fTVJyU1fbPTJwfJANtUbs87wbWFIgpyUaX2E4ZOyDEVg
            btb/2XhtX9wUlH9DU7Q8H7+SqnPyrBP3bX2tZmB+KXTCXCdmA4hqVCg4ju5WCrO5
            LbRhljZ9wrMJRwNhDpk4A50wmvwgOtuAZJMv0nxODnOJ8pAghadybx/xMajToTdT
            gc5RcQ0uraELmcOh0wMrMW+abXAzPBwQa4gdYEo9xI5W2rERSlr3KwnSKT1Ec73P
            aRl6ETLZYP6pTz9p0gA0Vi69T7+xsShLSqt7xecQiBsv7LkiSF9vxUp6oRBahmTk
            qVeWfA317rDoV6YPD8r2C4m2eofTPWVfHry/EQJfalOgrLBsJT5sNk1u6PT8KRQg
            UgbczC+G+MoGr1GfiyMmOpK0CCyP88ZsQcQQwm7+jdjikkDhzJPeG72UaX/FiNBc
            oPIQ8uzjpI6kCEkkh3NQtkwPQP1asrd8cFkbl2tXDt5H75XH8yK/0OkN0PfdqmfQ
            2U+X0vfzobgulhiN71qA0l4Bd+H1cA9l8AHZmFSgfXwpmghhhgUoBDymbIRzW4KS
            JEMzX8yLwg+38KCaZe7BQMjR6/eJdXt1eLED+nbAAljVQfFwZGUxh0vqXUATq1Xt
            l2GuOJkKHv1yv6ntKIlG
            =RKb2
            -----END PGP MESSAGE-----
        fp: 6B9CB4956CDDD0599A518BA6CFF195C6AE9E4939
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQgAgotOWPX94Pjmedcc++0UqlxofschhGh6ew8h1v6BKjn+
            RcHSFOuB1G6AeK5L86edcWO26mJJI4jI72tpe3zn0Xri2EKxyyECGprpz+KdsOMr
            rFYJdO+5q/+Qnux4atVb77Eies8ZBn+KD5beF0P9xmQ9zxJHCEKm8FXu1KeI8RO0
            5QMOl4J23CXmQZVLeSgtJSSPqmt/ehsTQYksUO3VAWdo5ouSVoHTpI0qItqkr46f
            PMojos4CdicMwlVRa6rDW0r4XJ2jK9QLA5Vs+ULH4bfVqeIIm0nrd5O1Df4xPIEx
            v7Y4gTMTQURVFPh8YnW1McxmoiY2IxBCHhnVKgZ/CtJeAU2hEAJkmFNGECnHEJ5G
            5RqarA5Aw5r7ZPWS/lnGdkTgfEI5mgZX5WMnrHkttJhze8Gn0DXnXOs5gIzSnvzw
            ERsAb4eq1WmN18IM7H+h3zJ3/G52+kMj20rBJVuvjw==
            =qRfz
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T13:51:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0ZhTnV170YBAQv/R25pUa0mzSH8CKDN8KSo0u3zU7DhWj19Dk1L29lx1XyU
            D5RAx8bcImgJV1HFGsqWHqSl+8rY+jdEXsbM5RvGbpCxsbZMbnga8AZJaTbJHCu3
            oF7LD5OHa7Sdcgz18DalQGjrWGITPTsXMwap+tsFxjanFH/EeflkihrbDb7Dcbc8
            dm2AtL2f1ZZM+zlweT8lFp202jxJefF6s0W/h7PuHAKLjmoNL4EIFmyADOi8ByDd
            JpB+CvhxiVaIHKDFoG4tjAG67LEcyFilRoEugqwq9Vaeq9Vgl08rFNh+XiFADkMz
            cdRbd6cBP+RmtXmc+7WtHXMGoiP5ztNvm1oJDPW4FETHbP90iRO95+s9UxM5EfUH
            72C7wviH3p7OyoJ2klU3hQ04eiiKCxYcsjsic+wgdz2Yj5UGqFSvS8alUtUICFXD
            aQO+A12eYALaZj9xIQYUG4GC+MiibW5F85Tm8OX8EmpSvqG3eSXlvBtxyeI7UGUo
            JwzEJtSN3eVGi9+p4Pum0l4BZI5I/JriBOJH6pEP0/0ki5OR1P2LCdLpIWG8M0Ei
            0xrb5d/dNlzSggdyQ91BruDKswy9UrUynT3/udYO41oT7CP105T2yAroIZR6hoOx
            rh3LKE2ShoDMK8hs/ueX
            =pcgd
            -----END PGP MESSAGE-----
        fp: CC69D686B0FCFF3B5C2147AD8AFEC23AB1EB36A3
    -   created_at: '2020-09-30T21:54:33Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA0sgQJTuz3CvAQf/flhadzSzjtQGJ/eMHuf3HZG2AschKfzs83Qg8DaQ1uNV
            W2bWeCHCMto7vwktXQSzLdvBYFV8BCMeGFvw8OrWxjbycT+1ETOy81of1e2gFB0D
            SArLDM/qMCbKu/WGu6OK3AA1mny5xmb/wdaXn6EcUhQAstYwqmaWXRW09gHOeRyz
            6I3isP3UaYvUBHXZiDhYFcphdifcC8QV9SoWJM3U1i21X2Gbaq4n7wwT/Ii0Yvo3
            KiOxm6xHjqrOpV2CnZ+dBiHRF6YzP/m4+crHE7URgHvJOWsQdwB6/Ee5/C8EimOV
            WS2TGX2dkYUJF/4gjUjcbrFiI6uxRA3ravQS73QZhNJeAe65wpxmeS6VJ85k9Esh
            AsHlC6zXN5/A9YgIEB3NxQisDg2IKi5+POPR+k7UdFoQjhY0FyDjYWMbC9COrkPa
            lXyXZmWBFA5PQkK8d7Crm+c+hkSHIKlhb2WfsY/f5Q==
            =l7sy
            -----END PGP MESSAGE-----
        fp: 84D2732F14E43B7540DF0074679ADA89F304FFB1
    -   created_at: '2020-10-27T21:33:43Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5DboIX0e/riAQwArLzpt2pMWsD/nXApHc59P33OEwegel+yuejPtBSeAMaF
            IX6PQO02qKaPZ7IlxRhNW8twvPUY0LPEhmc4nbh97FeB5F2K24rpfxYenEx9Ylul
            3ZpOykZI0CkkH+gy5gAwJuXav4qF2G0PItYW4DZa4mhuVZjYFnHlVdFjCD4JdAYU
            R+SknbyK2RAtJ+vS7V79Tu7T/5VAfqXzldw5If9ejBOPP5lR392VKcgP0kdQdVtG
            HOE48qHbHjJxCwudmjCbkAgTkDB7Wc4NuPeRBJQbyKzDgBW7dqvWYkKaxVAgRmEu
            50CAJQo1IH+gwh5yQ/Ttl08S4URUAg1cQHfTvTZdRSNusUFiz8CLSWwHblg3PiOR
            Ym5nPJ0UL/SDZnI/1viS992UwivpzxaXkUtM/20MVAdD4UO1SBcqB14NwNuGf21r
            cuccQOitz7aZaU76Mooxx4hh8Sz8Mj/b3soNrRutB62QRVd+SN40q6xD0lQssHOh
            rJ7ntTq1lKbEnRJh97oQ0l4BpHXAI/++IymoFULzj7VAUv1IFymRBHi+d9jx+YK+
            7WyZL/oTpZB4MnkJUa/mQHjPZG4XdbetsweraJvktFBP2Jo/tjPHLob7AeFZrPsQ
            g5XOJNfK7fpi30pf+D9y
            =GpOm
            -----END PGP MESSAGE-----
        fp: 54AE25FAAAF84ACAB4F1BF907696644F2069EBDA
    unencrypted_regex: ^(implementer)$
    version: 3.6.1
